name: Go

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Go build, test, & vet
      run: |
        mkdir build
        go build -o ./bin/play ./play/play.go
        go test ./...
        go vet ./...
      working-directory: .
